# It defines the following variables
#  NeuH_INCLUDE_DIRS - include directories
#  NeuH_LOG_LEVEL    - log verbosity level

SET(NeuH_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR}/include)

SET(NeuH_LOG_LEVEL 5 CACHE STRING "Log verbosity level")
SET(LEVEL_LIST 0 1 2 3 4 5)
SET_PROPERTY(CACHE NeuH_LOG_LEVEL PROPERTY STRINGS ${LEVEL_LIST})

IF(${NeuH_LOG_LEVEL} IN_LIST LEVEL_LIST)
  ADD_DEFINITIONS(-DNLOG_LEVEL=${NeuH_LOG_LEVEL})
ELSE()
  MESSAGE(FATAL_ERROR "NeuH_LOG_LEVEL must be set to one of ${LEVEL_LIST}!")
ENDIF()
