CMAKE_MINIMUM_REQUIRED(VERSION 3.25 FATAL_ERROR)
PROJECT(x_test LANGUAGES CXX)

IF(MSVC)
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /W3 /WX /Zc:__cplusplus")
ELSE()
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Werror")
ENDIF()

SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)

ADD_COMPILE_DEFINITIONS(X_ENABLE_SOCKET=1)

INCLUDE_DIRECTORIES(
  ../..
)

SET(TEST_TARGETS
  test_x_error
  test_x_event
  test_x_gadget
  test_x_memory
)

FOREACH(TARGET ${TEST_TARGETS})
  ADD_EXECUTABLE(${TARGET} ${TARGET}.cpp)
ENDFOREACH()
