IF(NOT DEFINED NEU_H_DIR)
  GET_FILENAME_COMPONENT(NEU_H_DIR ${CMAKE_CURRENT_LIST_DIR}/.. ABSOLUTE)
  MESSAGE(STATUS "=====> NEU_H_DIR is set to ${NEU_H_DIR}.")
ENDIF()

SET(NEU_LOG_LEVEL 4 CACHE STRING "Log level")
SET(LOG_LEVEL_LIST -1 0 1 2 3 4)
SET_PROPERTY(CACHE NEU_LOG_LEVEL PROPERTY STRINGS ${LOG_LEVEL_LIST})

IF(NOT ${NEU_LOG_LEVEL} IN_LIST ${LOG_LEVEL_LIST})
  MESSAGE(FATAL_ERROR "=====> Log level must be one of ${LOG_LEVEL_LIST}")
ENDIF()
